name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

env:
  DOCKER_IMAGE_NAME: flask-ci-cd-demo
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # GitHub Secret
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}     # GitHub Secret

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest test_app.py

      - name: Lint with Flake8 (Optional, but good practice)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-and-push-docker:
    needs: build-and-test # This job will only run if 'build-and-test' job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          platforms: linux/amd64 # Specify platform if needed for compatibility
